{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "base.fullname" (dict "Release" .Release "Values" .Values) }}
  labels:
    {{- include "base.labels" (dict "Release" .Release "Values" .Values "Chart" .Chart) | nindent 4 }}
  {{- if .Values.secretAnnotations }}
  annotations:
    {{- toYaml .Values.secretAnnotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $value := .Values.secretEnv }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}