{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "base.serviceAccountName" . }}
  labels:
    {{- include "base.labels" (dict "Release" .Release "Values" .Values "Chart" .Chart) | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceAccount.imagePullSecrets }}
  imagePullSecrets:
  {{- range .Values.serviceAccount.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
  {{- end }}
{{- end }}